"use client";

import { useState, useTransition } from "react";
import { toast } from "sonner";
import { Copy, Download, FileDown, Loader2, RefreshCw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { generateJnvTeacherContentAction } from "@/lib/actions/admin/jnv-ai";
import { JNV_TEACHER_CONTENT_TYPES, jnvTeacherContentLabel, type JnvTeacherContentKey } from "@/lib/jnv/teacher-content-types";
import { JNV_CLASS_LEVELS, jnvClassLabel } from "@/lib/jnv/catalog";

const COUNT_APPLICABLE = new Set<JnvTeacherContentKey>([
  "MCQS",
  "SHORT_QUESTIONS",
  "LONG_QUESTIONS",
  "VIVA_QUESTIONS",
  "BLOOMS_QUESTIONS",
]);

export function JnvAiToolkitManager() {
  const [pending, startTransition] = useTransition();
  const [contentType, setContentType] = useState<JnvTeacherContentKey>("LESSON_PLAN");
  const [classLevel, setClassLevel] = useState<string>("8");
  const [subject, setSubject] = useState("Computer Science");
  const [topic, setTopic] = useState("");
  const [count, setCount] = useState("");
  const [extraInstructions, setExtraInstructions] = useState("");
  const [content, setContent] = useState("");
  const [exporting, setExporting] = useState(false);

  const showCount = COUNT_APPLICABLE.has(contentType);

  function generate() {
    if (!topic.trim()) {
      toast.error("Enter a topic first");
      return;
    }
    startTransition(async () => {
      const res = await generateJnvTeacherContentAction({
        contentType,
        classLevel: Number(classLevel),
        subject,
        topic,
        count: showCount && count ? Number(count) : null,
        extraInstructions: extraInstructions || null,
      });
      if (!res.ok) {
        toast.error(res.error);
        return;
      }
      setContent(res.data!.content);
      toast.success("Generated — review and edit before saving or exporting.");
    });
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(content);
      toast.success("Copied to clipboard");
    } catch {
      toast.error("Could not copy");
    }
  }

  function downloadTxt() {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${jnvTeacherContentLabel(contentType)} - ${topic || "untitled"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function downloadPdf() {
    setExporting(true);
    try {
      const res = await fetch("/api/admin/jnv/export-pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: `${jnvTeacherContentLabel(contentType)} — ${topic || "Untitled"}`,
          meta: `${jnvClassLabel(Number(classLevel))} · ${subject} · Generated by Byte`,
          body: content,
        }),
      });
      if (!res.ok) {
        toast.error("Could not export PDF");
        return;
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${jnvTeacherContentLabel(contentType)} - ${topic || "untitled"}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      toast.error("Could not export PDF");
    } finally {
      setExporting(false);
    }
  }

  return (
    <div className="grid gap-6 lg:grid-cols-[380px_1fr]">
      <div className="space-y-4 rounded-xl border bg-background p-4">
        <div>
          <Label htmlFor="jnv-ai-type">Content type</Label>
          <Select value={contentType} onValueChange={(v) => setContentType(v as JnvTeacherContentKey)}>
            <SelectTrigger id="jnv-ai-type" className="mt-1.5 w-full">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {JNV_TEACHER_CONTENT_TYPES.map((t) => (
                <SelectItem key={t.key} value={t.key}>
                  {t.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <Label htmlFor="jnv-ai-class">Class</Label>
            <Select value={classLevel} onValueChange={setClassLevel}>
              <SelectTrigger id="jnv-ai-class" className="mt-1.5 w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {JNV_CLASS_LEVELS.map((lvl) => (
                  <SelectItem key={lvl} value={String(lvl)}>
                    {jnvClassLabel(lvl)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label htmlFor="jnv-ai-subject">Subject</Label>
            <Input
              id="jnv-ai-subject"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="mt-1.5"
            />
          </div>
        </div>

        <div>
          <Label htmlFor="jnv-ai-topic">Topic</Label>
          <Textarea
            id="jnv-ai-topic"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g. Input and Output Devices"
            className="mt-1.5"
            rows={2}
          />
        </div>

        {showCount && (
          <div>
            <Label htmlFor="jnv-ai-count">How many? (optional)</Label>
            <Input
              id="jnv-ai-count"
              type="number"
              min={1}
              max={30}
              value={count}
              onChange={(e) => setCount(e.target.value)}
              placeholder="e.g. 10"
              className="mt-1.5"
            />
          </div>
        )}

        <div>
          <Label htmlFor="jnv-ai-extra">Extra instructions (optional)</Label>
          <Textarea
            id="jnv-ai-extra"
            value={extraInstructions}
            onChange={(e) => setExtraInstructions(e.target.value)}
            placeholder="Any specifics — difficulty level, focus area, format tweaks…"
            className="mt-1.5"
            rows={2}
          />
        </div>

        <Button onClick={generate} disabled={pending} className="w-full gap-1.5">
          {pending ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
          Generate with Byte
        </Button>
      </div>

      <div className="flex flex-col rounded-xl border bg-background">
        <div className="flex flex-wrap items-center justify-between gap-2 border-b p-3">
          <span className="text-sm font-medium text-muted-foreground">
            {content ? "Review and edit before saving or exporting" : "Generated content appears here"}
          </span>
          {content && (
            <div className="flex flex-wrap gap-2">
              <Button variant="outline" size="sm" onClick={generate} disabled={pending} className="gap-1.5">
                <RefreshCw className="size-3.5" /> Regenerate
              </Button>
              <Button variant="outline" size="sm" onClick={copy} className="gap-1.5">
                <Copy className="size-3.5" /> Copy
              </Button>
              <Button variant="outline" size="sm" onClick={downloadTxt} className="gap-1.5">
                <Download className="size-3.5" /> .txt
              </Button>
              <Button size="sm" onClick={downloadPdf} disabled={exporting} className="gap-1.5">
                {exporting ? <Loader2 className="size-3.5 animate-spin" /> : <FileDown className="size-3.5" />}
                Export PDF
              </Button>
            </div>
          )}
        </div>
        <Textarea
          value={content}
          onChange={(e) => setContent(e.target.value)}
          placeholder="Fill in the form and click Generate — the result lands here, fully editable."
          className="min-h-[420px] flex-1 resize-none rounded-none border-0 p-4 text-sm focus-visible:ring-0"
        />
      </div>
    </div>
  );
}
